server:
  port: 8089
spring:
  application:
    name: spring-cloud-client
  cloud:
    consul:
      host: 10.10.20.212
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
        health-check-path: /actuator/health
        service-name: ${spring.application.name}
        prefer-ip-address: true
feign:
  hystrix:
    enabled: true
hystrix:
  metrics:
    enabled: true
