server:
  port: 8080

spring:
  application:
    name: spring-cloud-gateway
  redis:
    database: 0
    host: 127.0.0.1
    pool: 6379
    jedis:
      pool:
        max-active: 10
        min-idle: 1
        max-wait: 1000ms
        max-idle: 10
  cloud:
    consul:
      host: 10.10.20.212
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
        health-check-path: /actuator/health
        service-name: ${spring.application.name}

    gateway:
      # 允许跨域
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET

      default-filters:
      - AddResponseHeader=X-Gateway-client, ${spring.cloud.client.ip-address}:${server.port}
      # 在routes中已经注册，且后端服务不可用时，才进入这个filter。如果是404,502等，则不会进入。
      - name: Hystrix
        args:
          name: fallbackcmd
          # 增加一个类 FallbackController
          #@RequestMapping("/fallback")
          #public Mono<Object> fallback() {
          #    return Mono.just("fallback");
          #}
          fallbackUri: forward:/fallback
      routes:
      - id: server1
#        uri: http://10.10.20.212:8081
        uri: lb://spring-cloud-consul
        predicates:
        - Path=/server1/**
        filters:
        # 自定义过滤器 (继承于AbstractGatewayFilterFactory,再定义Bean)
        # 自定义类名 TokenGatewayFilterFactory
        # 需要增加@Bean TokenGatewayFilterFactory
        - Token
        # 将Path中的第一个部分(server1)去掉后，再转发到后端API
#        - RewritePath=/server1/(?<segment>.*), /$\{segment}
        - StripPrefix=1
        - AddRequestHeader=X-Request-Gateway, DefaultGateway

        #使用redis限流，需要增加@Bean
        - name: RequestRateLimiter
          args:
            # 允许每秒处理多少个请求
            #@Bean
            #public KeyResolver ipKeyResolver() {
            # return exchange -> Mono.just(exchange.getRequest().getRemoteAddress().getAddress().getHostAddress());
            #}
            redis-rate-limiter.replenishRate: 60
            # 令牌桶的容量，允许在一秒钟内完成的最大请求数
            redis-rate-limiter.burstCapacity: 120
  zipkin:
    base-url: http://127.0.0.1:9411
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      # 采样率
#      rate: 1
      probability: 1.0
    #web:
    #  skip-pattern:

logging:
  level:
    org.springframework.cloud.gateway: TRACE

#management:
#  endpoints:
#    web:
#      exposure:
#        include: gateway

