server:
  port: 8085
spring:
  application:
    name: spring-cloud-turbine
  cloud:
    consul:
      host: 10.10.20.212
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
        health-check-path: /actuator/health
        service-name: ${spring.application.name}

turbine:
  aggregator:
    cluster-config: default
  app-config: spring-cloud-client-a
  cluster-name-expression: new String("default")
  combine-host-port: true