server:
  port: 8082
spring:
  application:
    name: spring-cloud-client
  cloud:
    consul:
      host: 10.10.20.212
      port: 8500
      discovery:
        register: false
feign:
  hystrix:
    enabled: true
hystrix:
  metrics:
    enabled: true
